Auto-sync: 2018-10-04_15:27:07

diff --git a/i3blocks/updater b/i3blocks/updater
--- a/i3blocks/updater
+++ b/i3blocks/updater
@@ -7,11 +7,10 @@ i3b_update_backlight () {
         echo 'Backlight updater is already running' && exit )
     _socket=1
     _file="/sys/class/backlight/${BRI_SCR}/brightness"
-    while : ; do
-        [ -e "${_file}" ] || ( echo 'Backlight file not found' && sleep 60 && continue )
-	    inotifywait --quiet "${_file}" > /dev/null
-	    pkill -RTMIN+"${_socket}" i3blocks ;
-        sleep .1
+    [ -e "${_file}" ] || _file=""
+    inotifywait --monitor --timeout -1 "${_file}" | \
+        while IFS= read -r line; do pkill -RTMIN+"${_socket}" i3blocks
+        wait .1
     done
     echo 'Backlight updater is exiting'
 }
@@ -22,12 +21,11 @@ i3b_update_battery () {
     _socket=2
     _ac="/sys/class/power_supply/AC0/online"
     _ba="/sys/class/power_supply/BAT0/capacity"
-    while : ; do
-	    [ -e "${_ac}" ] || ( echo 'AC power source not found' && sleep 60 && continue )
-	    [ -e "${_ba}" ] || ( echo 'Battery not found' && sleep 60 && continue )
-	    inotifywait --quiet "${_ac}" "${_ba}" > /dev/null
-	    pkill -RTMIN+"${_socket}" i3blocks ;
-        sleep .1
+    [ -e "${_ac}" ] || _ac=""
+    [ -e "${_ba}" ] || _ba=""
+	inotifywait --monitor --timeout -1 "${_ac}" "${_ba}" | \
+        while IFS= read -r line; do pkill -RTMIN+"${_socket}" i3blocks
+        wait .1
     done
     echo 'Battery updater is exiting'
 }
@@ -37,9 +35,10 @@ i3b_update_mpd () {
         echo 'MPD updater is already running' && exit )
     _socket=3
     while : ; do
-	    pgrep -x mpd > /dev/null || ( echo 'MPD is unreachable' && sleep 60 && continue )
-	    mpc idle > /dev/null
-	    pkill -RTMIN+"${_socket}" i3blocks ;
+        pgrep -x mpd > /dev/null || ( echo 'MPD is unreachable' && sleep 60 && continue )
+        mpc idle > /dev/null
+        pkill -RTMIN+"${_socket}" i3blocks
+        wait .1
     done
     echo 'MPD updater is exiting'
 }
@@ -50,10 +49,11 @@ i3b_update_rss () {
     _socket=4
     _file="${HOME}/Documents/RSS"
     while : ; do
-        [ -e "${_file}" ] || ( echo 'RSS file not found' && sleep 60 && continue )
-	    inotifywait --quiet "${_file}" > /dev/null
-	    pkill -RTMIN+"${_socket}" i3blocks ;
-        sleep 5
+        [ -e "${_file}" ] || ( echo 'RSS folder not found' && sleep 60 && continue )
+    done
+    inotifywait --monitor --timeout -1 --recursive "${_file}" | \
+        while IFS= read -r line; do pkill -RTMIN+"${_socket}" i3blocks
+        wait .1
     done
     echo 'RSS updater is exiting'
 }
@@ -64,11 +64,13 @@ i3b_update_imap () {
     _socket=5
     _file="${HOME}/.mail/Gmail/Inbox/new"
     while : ; do
-	    [ -e "${_file}" ] || ( echo 'Mailbox not found' && sleep 60 && continue )
-	    inotifywait --quiet "${_file}" > /dev/null
-	    pkill -RTMIN+"${_socket}" i3blocks ;
-        sleep 5
+        [ -e "${_file}" ] || ( echo 'Mailbox not found' && sleep 60 && continue )
     done
+    inotifywait --monitor --timeout -1 --recursive "${_file}" | \
+        while IFS= read -r line; do pkill -RTMIN+"${_socket}" i3blocks
+        wait .1
+    done
+
     echo 'Imap updater is exiting'
 }
 
@@ -76,10 +78,9 @@ i3b_update_pulseaudio () {
     [ "$(pgrep -x i3b_update_pulseaudio | wc -l)" -gt 2 ] && ( \
         echo 'Pulseaudio updater is already running' && exit )
     _socket=6
-    /usr/bin/pactl subscribe | \
-        grep --line-buffered -e "sink" -e "'change' on server #" | \
-        while IFS= read -r line; do
-        pkill -RTMIN+"${_socket}" i3blocks ;
+    /usr/bin/pactl subscribe | grep --line-buffered -e "sink" -e "'change' on server #" | \
+        while IFS= read -r line; do pkill -RTMIN+"${_socket}" i3blocks
+        wait .1
     done
     echo 'Pulseaudio updater is exiting'
 }
@@ -91,34 +92,52 @@ i3b_update_date () {
     _socket=7
     while : ; do
         sleep "$(( $(date -d "tomorrow 0" +%s) - $(date +%s) + 5 ))"
-        pkill -RTMIN+"${_socket}" i3blocks ;
+        pkill -RTMIN+"${_socket}" i3blocks
     done
 }
 
 i3b_update_tasks () {
     [ "$(pgrep -x i3b_update_tasks | wc -l)" -gt 2 ] && ( \
         echo 'Tasks updater is already running' && exit )
-    echo 'Tasks updater is exiting'
     _socket=8
+    _file="${HOME}/Documents/Tasks"
+    while : ; do
+	    [ -e "${_file}" ] || ( echo 'Tasks not found' && sleep 60 && continue )
+    done
+	inotifywait --monitor --timeout -1 --recursive "${_file}" | \
+        while IFS= read -r line; do pkill -RTMIN+"${_socket}" i3blocks
+        wait .1
+    done
+    echo 'Tasks updater is exiting'
 }
 
 i3b_update_calendar () {
     [ "$(pgrep -x i3b_update_calendar | wc -l)" -gt 2 ] && ( \
         echo 'Calendar updater is already running' && exit )
     echo 'Calendar updater is exiting'
-    _socket=8
+    _socket=9
+    _file="${HOME}/Documents/Calendar"
+    while : ; do
+	    [ -e "${_file}" ] || ( echo 'Calendar not found' && sleep 60 && continue )
+    done
+	inotifywait --monitor --timeout -1 --recursive "${_file}" | \
+        while IFS= read -r line; do pkill -RTMIN+"${_socket}" i3blocks
+        wait .1
+    done
+    echo 'Calendar updater is exiting'
 }
 
-i3b_update_rss () {
+i3b_update_language () {
     [ "$(pgrep -x i3b_update_rss | wc -l)" -gt 2 ] && ( \
         echo 'Language updater is already running' && exit )
-    _socket=9
-    while : ; do
-        xkb-switch --wait
-	    pkill -RTMIN+"${_socket}" i3blocks ;
+    _socket=10
+    xkb-switch -W | \
+        while IFS= read -r line; do pkill -RTMIN+"${_socket}" i3blocks
+        wait .1
     done
     echo 'Language updater is exiting'
 }
+
 # Kill all children on exit
 trap 'kill $(jobs -p)' EXIT SIGINT SIGTERM
 
